global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false
  namespace: tracking

replicaCount: 1

image:
  repository: @docker.repo@/@project.artifactId@
  tag: @project.version@

service:
  type: NodePort
  port: 8081
  targetPort: 8081
  nodePort: 30081

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

kafka:
  serviceFQDN: "tracking-kafka.tracking.svc.cluster.local"
  port: 9092
  clientPort: 29092

ingress:
  enabled: false

# Section for overriding values in subcharts defined in the Chart.yaml
dispatch:
  kafka:
    enabled: false
    serviceFQDN: "tracking-kafka.tracking.svc.cluster.local"
    advertisedListenersString: "PLAINTEXT://tracking-kafka.tracking.svc.cluster.local:9092,PLAINTEXT_HOST://tracking-kafka.tracking.svc.cluster.local:29092"
  tracking:
    enabled: false
  wiremock:
    enabled: true
    serviceFQDN: "tracking-wiremock.tracking.svc.cluster.local"

