spring:
  application:
    name: tracking
  kafka:
    # See: https://docs.conduktor.io/desktop/kafka-cluster-connection/setting-up-a-connection-to-kafka/connecting-to-kafka-running-on-windows-wsl-2/#two-ways-to-fix-this
    # and: https://stackoverflow.com/questions/46158296/kafka-broker-not-available-at-starting
    bootstrap-servers: "[::1]:9092"

    admin:
      properties:
        bootstrap.servers: "[::1]:9092"
    consumer:
      bootstrap-servers: "[::1]:9092"
  docker:
    compose:
      enabled: false
      stop:
        command: down

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.zalando.logbook: TRACE
