### actuator
GET http://localhost:{{application-port}}/actuator
Accept: application/json

### actuator info
GET http://localhost:{{application-port}}/actuator/info
Accept: application/json

### actuator health
GET http://localhost:{{application-port}}/actuator/health
Accept: application/json

### actuator health
GET http://localhost:{{application-port}}/actuator/health/readiness
Accept: application/json

### actuator health
GET http://localhost:{{application-port}}/actuator/health/liveness
Accept: application/json

### actuator metrics
GET localhost:{{application-port}}/actuator/metrics
Accept: application/json

### actuator env
GET localhost:{{application-port}}/actuator/env
Accept: application/json

### actuator env
GET localhost:{{application-port}}/actuator/configprops
Accept: application/json

### actuator beans
GET localhost:{{application-port}}/actuator/beans
Accept: application/json

### actuator caches
GET localhost:{{application-port}}/actuator/caches
Accept: application/json

### actuator get loggers
GET localhost:{{application-port}}/actuator/loggers
