### actuator health
GET http://localhost:{{dispatch-service-port}}/actuator/health
Accept: application/json

### actuator health
GET http://localhost:{{dispatch-service-port}}/actuator/health/kafka
Accept: application/json

### actuator info
GET http://localhost:{{dispatch-service-port}}/actuator/info
Accept: application/json