apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka
  template:
    metadata:
      labels:
        {{- include "kafka.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kafka
    spec:
      containers:
        - name: kafka
          # TODO: USE BITNAMI
          image: confluentinc/cp-kafka:7.9.2
          imagePullPolicy: IfNotPresent
          ports:
            # PLAINTEXT Listener
            - name: kafka
              containerPort: {{ .Values.kafka.port }}
              protocol: TCP
            # PLAINTEXT_HOST Listener
            - name: client
              containerPort: {{ .Values.kafka.clientPort }}
              protocol: TCP
            # CONTROLLER Listener
            - name: controller
              containerPort: {{ .Values.kafka.controllerPort }}
              protocol: TCP


          env:
            - name: KAFKA_KRAFT_MODE
              value: "true"
            - name: KAFKA_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@{{ .Values.kafka.serviceFQDN }}:{{ .Values.kafka.controllerPort }}"
            - name: KAFKA_LISTENERS
              value: {{ .Values.kafka.listenersString | quote }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .Values.kafka.securityProtocolMap | quote }}
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: {{ .Values.kafka.advertisedListenersString | quote }}
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: CLUSTER_ID
              value: "Mk3OEYBSD34fcwNTJENDM2Qk_TRACKING"
