apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.type }}
  ports:
    # PLAINTEXT Listener
    - port: {{ .Values.kafka.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka

    # PLAINTEXT_HOST Listener
    - port: {{ .Values.kafka.clientPort }}
      targetPort: client
      nodePort: {{ .Values.kafka.nodePort }}
      protocol: TCP
      name: client

    # CONTROLLER Listener
    - port: {{ .Values.kafka.controllerPort }}
      targetPort: controller
      protocol: TCP
      name: controller
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
